name: CLI build

on:
  workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
      name: "Install dependencies from package-lock.json"
    - run: npm install pkg -g
      name: "Install pkg"
    - run: npm install typescript@4.2.4 -g
      name: "Install typescript"
    - run: tsc
      working-directory: ./src-cli
      name: "Build cli to javascript"
    - run: pkg .
      name: "Package cli to single executable"
    
    - run:  mkdir "out"
      name: "Create output directory"
    - run: cp paint-by-numbers-generator-linux ./out\paint-by-numbers-generator-linux
      name: "Copy binary to out directory"
    - run: cp ./node_modules/canvas/build/Release/* ./out
      name: "Copy node-canvas binaries to output"
    - run: rm *.pdb, *.ipdb, *.iobj
      name: "Cleanup unnecessary debug files"
      working-directory: ./out
    - uses: actions/upload-artifact@v4
      name: "Upload out as artifact"
      with:
        name: pbn-cli-linux
        path: ./out\*
      env:
        CI: true
    - run: mkdir artifacts
    - name: Download a Build Artifact zip
      uses: actions/download-artifact@v4.2.1
      with:
        name: "pbn-cli-win"
        path: "./artifacts/pbn-cli-win.zip"
    - uses: ncipollo/release-action@v1
      name: "Create development prerelease"
      with:
        artifact: "artifacts/*"
        prerelease: true
        allowUpdates: true
        name: "CLI Development build"
        tag: "latest"
        token: ${{ secrets.GITHUB_TOKEN }}  

